package com.trtm.iot.kongdaoyaj.entity;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Date;
import java.util.List;

@Entity // Assuming you want to use this entity with a JPA-based ORM
public class kongdaoyajpush {

    @Id // Primary key identifier
    private String UUID;

    private String Province;
    private String DetectIndustry;
    private String DetectNatureNum;
    private String DetectType;
    private String DetectUnit;
    private String DeviceCompany;
    private String Remarks;
    private String ProjPlace;
    private String WorkName;
    private String DetectPerson;
    private String DetectParam;
    private String DetectClass;
    private String ConsUnit;
    private String SuperVisionUnit;
    private String Employer;
    private String DetectNO;
    private String PushProjectName;

    // Using a nested static class for DetectData since it's a collection within the main object
    public static class DetectData {
        private String DetectItem;
        private int DetectItemNum;
        private String AnalysisNum;
        private Date DetectDate; // Changed from string to Date for better date handling
        private String ComponentId;
        private String ComponentName;
        private String DetectLocation;
        private String FileName;

        // Getters and setters or Lombok annotations
    }

    private List<DetectData> DetectData; // This should match the JSON array structure

    // Getters and setters or Lombok annotations for all fields

    // Constructors, if needed

    // toString, equals, and hashCode methods, preferably generated by IDE or Lombok
}
